name: Android Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: [dev,main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install Cordova
      run: npm install -g cordova
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
        
    - name: Install project dependencies
      run: |
        npm install
        cordova prepare
        
    - name: Build Android APK
      run: |
        cordova build android --release
        cd platforms/android/app/build/outputs/apk/release
        echo "APK_PATH=$(pwd)/app-release.apk" >> $GITHUB_ENV
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: ${{ env.APK_PATH }}
        
    - name: Run Lint
      run: |
        cd platforms/android
        ./gradlew lint 