name: Android Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: [dev,main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 29
        build-tools-version: '25.0.3'
        platform: 'android-29'
        
    - name: Install Ant
      run: |
        choco install ant -y
        
    - name: Download Android Ant Build Script
      run: |
        mkdir -p android-ant
        curl -L https://raw.githubusercontent.com/android/platform_sdk_base/master/tools/ant/build.xml -o android-ant/build.xml
        
    - name: Create build.xml
      run: |
        echo "<?xml version='1.0' encoding='UTF-8'?>" > build.xml
        echo "<project name='HCH_MOBILE_CONSENT_STG' default='help'>" >> build.xml
        echo "  <property name='sdk.dir' value='$env:ANDROID_HOME'/>" >> build.xml
        echo "  <property name='target' value='android-29'/>" >> build.xml
        echo "  <property name='buildtools.version' value='25.0.3'/>" >> build.xml
        echo "  <property name='key.store' value='keystore/umkey'/>" >> build.xml
        echo "  <property name='key.alias' value='alias'/>" >> build.xml
        echo "  <property name='key.store.password' value='${{ secrets.KEY_STORE_PASSWORD }}'/>" >> build.xml
        echo "  <property name='key.alias.password' value='${{ secrets.KEY_STORE_PASSWORD }}'/>" >> build.xml
        echo "  <import file='android-ant/build.xml'/>" >> build.xml
        echo "</project>" >> build.xml
        
    - name: Build with Ant
      run: |
        cmd /c "ant release"
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*-release.apk
        
    - name: Run Lint
      run: |
        cmd /c "$env:ANDROID_HOME\tools\bin\lint --config lint.xml ."
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }} 