name: Android Build

on:
  pull_request:
    types: [opened, synchronize]
    branches: [dev,main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 29
        build-tools-version: '25.0.3'
        platform: 'android-29'
        
    - name: Install Ant
      run: |
        choco install ant -y
        
    - name: Create build.xml
      run: |
        echo "<?xml version='1.0' encoding='UTF-8'?>" > build.xml
        echo "<project name='HCH_MOBILE_CONSENT_STG' default='help'>" >> build.xml
        echo "  <property name='sdk.dir' value='$env:ANDROID_HOME'/>" >> build.xml
        echo "  <property name='target' value='android-29'/>" >> build.xml
        echo "  <property name='buildtools.version' value='25.0.3'/>" >> build.xml
        echo "  <property name='key.store' value='keystore/umkey'/>" >> build.xml
        echo "  <property name='key.alias' value='umkey'/>" >> build.xml
        echo "  <property name='key.store.password' value='${{ secrets.KEY_STORE_PASSWORD }}'/>" >> build.xml
        echo "  <property name='key.alias.password' value='${{ secrets.KEY_ALIAS_PASSWORD }}'/>" >> build.xml
        echo "  <import file='$env:ANDROID_HOME/tools/ant/build.xml'/>" >> build.xml
        echo "  <target name='help'>" >> build.xml
        echo "    <echo>Available targets:</echo>" >> build.xml
        echo "    <echo>  release: Build release APK</echo>" >> build.xml
        echo "  </target>" >> build.xml
        echo "  <target name='release'>" >> build.xml
        echo "    <mkdir dir='bin'/>" >> build.xml
        echo "    <javac srcdir='src' destdir='bin' includeantruntime='false'/>" >> build.xml
        echo "    <dx input='bin' output='bin/classes.dex'/>" >> build.xml
        echo "    <aapt executable='$env:ANDROID_HOME/build-tools/25.0.3/aapt.exe' command='package' versioncode='1' debug='false' manifest='AndroidManifest.xml' assets='assets' res='res' out='bin/resources.ap_'/>" >> build.xml
        echo "    <apkbuilder outfile='bin/app-release.apk' signed='true' signedjar='bin/app-release-signed.apk' keystore='keystore/umkey' storepass='${{ secrets.KEY_STORE_PASSWORD }}' alias='umkey' keypass='${{ secrets.KEY_ALIAS_PASSWORD }}'>" >> build.xml
        echo "      <sourcefolder path='bin/classes.dex'/>" >> build.xml
        echo "      <sourcefolder path='bin/resources.ap_'/>" >> build.xml
        echo "    </apkbuilder>" >> build.xml
        echo "    <zipalign in='bin/app-release-signed.apk' out='bin/app-release.apk'/>" >> build.xml
        echo "  </target>" >> build.xml
        echo "</project>" >> build.xml
        
    - name: Build with Ant
      run: |
        cmd /c "ant release"
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*-release.apk
        
    - name: Run Lint
      run: |
        cmd /c "$env:ANDROID_HOME\tools\bin\lint --config lint.xml ."
      env:
        ANDROID_HOME: ${{ env.ANDROID_HOME }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Notify Slack on Build Status
      if: always()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "text": "${{ job.status == 'success' && ':white_check_mark:' || ':x:' }} Android CI 빌드 결과\n• 성공 유무: ${{ job.status }}\n• 저장소: ${{ github.repository }}\n• 브랜치: ${{ github.ref_name }}\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|빌드된 APK 다운로드 링크>"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING-WEBHOOK 